version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: crawl
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:secret@postgres:5432/crawl
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
